services:

  db:
    image: postgres:16

    container_name: chat_db

    environment:
      POSTGRES_DB: chatapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:

    build: .

    container_name: chat_api

    ports:
      - "8000:8000"

    depends_on:
      - db

    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/chatapp

volumes:
  postgres_data: